### ISSUE TITLE
Inability to capture service name after a scan, it is cleaned up and removed during rawScan cleanup. 

### ISSUE THREAD

**Issue by OhZedTee** [t94j0/nmap#2]
Hi, I see that the rawScan has a slice of rawPort objects. This rawPort object has a serviceName attribute and in our use case for network scanning, this is the entire purpose of using nmap (to get service names potentially associated with common ports). Is there any way we can add the service name to  the final scan object under nmap.Port?

**Comment by t94j0** [comment]
> ...this is the entire purpose of using nmap (to get service names potentially associated with common ports)

I would argue that service fingerprinting is not the "entire purpose" of nmap. Checking which ports are open is the purpose and service fingerprinting is a nice feature. But the point is well taken; the information is already in the scan, so this package should expose the service name.

I just submitted a change. To be honest, this isn't the best nmap library out there. Ullakut has a really well developed [nmap] library that came that's still being actively developed

Best of luck, and I hope this change helps you out.

[nmap]: https://github.com/Ullaakut/nmap
